apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: bar
    criticality: high
    env: dev
    msg: not in selector
    version: 0.9.0
  name: bar
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: foo
    env: dev
  name: foo
  namespace: app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bar
    criticality: high
    env: dev
    msg: not in selector
    version: 0.9.0
  name: bar
  namespace: app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: bar
    criticality: high
    env: dev
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: foo
    env: dev
  name: foo
  namespace: app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: foo
    env: dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bar
    criticality: high
    env: dev
    msg: not in selector
    version: 0.9.0
  name: bar
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bar
      criticality: high
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bar
        criticality: high
        env: dev
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TEST
          value: foobar-$(POD_NAME)
        image: nginxdemos/hello
        name: bar
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: foo
    env: dev
  name: foo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foo
        env: dev
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TEST
          value: foobar-$(POD_NAME)
        image: nginxdemos/hello
        name: foo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
