---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: bar
labels:
  - pairs:
      version: 0.9.0
      msg: not in selector
  - pairs:
      criticality: high
    includeSelectors: true
resources:
  - deployment.yaml
  - sa.yaml
  - service.yaml
