apiVersion: integreatly.org/v1alpha1
kind: GrafanaNotifier
metadata:
  labels:
    env: stg
  name: alert-channel
spec:
  name: alert-channel
  notifier:
    isDefault: false
    name: alert-channel
    orgId: 1
    settings:
      mentionUsers: '@channel'
      url: https://example.com
      username: staging
    type: slack
    uid: abcdef
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    env: stg
  name: private-ingress
spec:
  rules:
  - host: mijope.de
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: 8080
        path: /login
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    env: stg
  name: public-ingress
spec:
  rules:
  - host: mijope.de
    http:
      paths:
      - backend:
          serviceName: bar
          servicePort: 8080
        path: /
