---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: stg
resources:
  - ../../base/
patches:
  - path: hostname.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: public-ingress
  - path: hostname.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: private-ingress
patchesJson6902:
  - target:
      group: integreatly.org
      version: v1alpha1
      kind: GrafanaNotifier
      name: alert-channel
    path: notification-channel.yaml
